/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CoursenameRequestBody
 */
public class CoursenameRequestBodyTest {
    private final CoursenameRequestBody model = new CoursenameRequestBody();

    /**
     * Model tests for CoursenameRequestBody
     */
    @Test
    public void testCoursenameRequestBody() {
        // TODO: test CoursenameRequestBody
    }

    /**
     * Test the property 'coursenameid'
     */
    @Test
    public void coursenameidTest() {
        // TODO: test coursenameid
    }

    /**
     * Test the property 'coursename'
     */
    @Test
    public void coursenameTest() {
        // TODO: test coursename
    }

    /**
     * Test the property 'coursenames'
     */
    @Test
    public void coursenamesTest() {
        // TODO: test coursenames
    }

}
