/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DegreetypeRequestBody
 */
public class DegreetypeRequestBodyTest {
    private final DegreetypeRequestBody model = new DegreetypeRequestBody();

    /**
     * Model tests for DegreetypeRequestBody
     */
    @Test
    public void testDegreetypeRequestBody() {
        // TODO: test DegreetypeRequestBody
    }

    /**
     * Test the property 'degreetypeid'
     */
    @Test
    public void degreetypeidTest() {
        // TODO: test degreetypeid
    }

    /**
     * Test the property 'typename'
     */
    @Test
    public void typenameTest() {
        // TODO: test typename
    }

    /**
     * Test the property 'shortcode'
     */
    @Test
    public void shortcodeTest() {
        // TODO: test shortcode
    }

    /**
     * Test the property 'degreetype'
     */
    @Test
    public void degreetypeTest() {
        // TODO: test degreetype
    }

}
