/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.CollectionModelCourse;
import org.openapitools.client.model.CollectionModelObject;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CoursenamePropertyReferenceControllerApi
 */
@Disabled
public class CoursenamePropertyReferenceControllerApiTest {

    private final CoursenamePropertyReferenceControllerApi api = new CoursenamePropertyReferenceControllerApi();

    /**
     * patch-course-by-coursename-Id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createPropertyReferenceCoursenamePatchTest() throws ApiException {
        String id = null;
        CollectionModelObject collectionModelObject = null;
        CollectionModelCourse response = api.createPropertyReferenceCoursenamePatch(id, collectionModelObject);
        // TODO: test validations
    }

    /**
     * update-course-by-coursename-Id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createPropertyReferenceCoursenamePutTest() throws ApiException {
        String id = null;
        CollectionModelObject collectionModelObject = null;
        CollectionModelCourse response = api.createPropertyReferenceCoursenamePut(id, collectionModelObject);
        // TODO: test validations
    }

    /**
     * delete-course-by-coursename-Id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deletePropertyReferenceCoursenameDeleteTest() throws ApiException {
        String id = null;
        api.deletePropertyReferenceCoursenameDelete(id);
        // TODO: test validations
    }

    /**
     * delete-course-by-coursename-Id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deletePropertyReferenceIdCoursenameDeleteTest() throws ApiException {
        String id = null;
        String propertyId = null;
        api.deletePropertyReferenceIdCoursenameDelete(id, propertyId);
        // TODO: test validations
    }

    /**
     * get-course-by-coursename-Id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void followPropertyReferenceCoursenameGetTest() throws ApiException {
        String id = null;
        String propertyId = null;
        CollectionModelCourse response = api.followPropertyReferenceCoursenameGet(id, propertyId);
        // TODO: test validations
    }

    /**
     * get-course-by-coursename-Id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void followPropertyReferenceCoursenameGet1Test() throws ApiException {
        String id = null;
        CollectionModelCourse response = api.followPropertyReferenceCoursenameGet1(id);
        // TODO: test validations
    }

}
