/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import org.openapitools.client.model.Link;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * EntityModelDegreetype
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-02-15T13:53:34.748533Z[Europe/London]")
public class EntityModelDegreetype {
  public static final String SERIALIZED_NAME_TYPENAME = "typename";
  @SerializedName(SERIALIZED_NAME_TYPENAME)
  private String typename;

  public static final String SERIALIZED_NAME_SHORTCODE = "shortcode";
  @SerializedName(SERIALIZED_NAME_SHORTCODE)
  private String shortcode;

  public static final String SERIALIZED_NAME_LINKS = "_links";
  @SerializedName(SERIALIZED_NAME_LINKS)
  private Map<String, Link> links = null;

  public EntityModelDegreetype() {
  }

  public EntityModelDegreetype typename(String typename) {
    
    this.typename = typename;
    return this;
  }

   /**
   * Get typename
   * @return typename
  **/
  @javax.annotation.Nullable

  public String getTypename() {
    return typename;
  }


  public void setTypename(String typename) {
    this.typename = typename;
  }


  public EntityModelDegreetype shortcode(String shortcode) {
    
    this.shortcode = shortcode;
    return this;
  }

   /**
   * Get shortcode
   * @return shortcode
  **/
  @javax.annotation.Nullable

  public String getShortcode() {
    return shortcode;
  }


  public void setShortcode(String shortcode) {
    this.shortcode = shortcode;
  }


  public EntityModelDegreetype links(Map<String, Link> links) {
    
    this.links = links;
    return this;
  }

  public EntityModelDegreetype putLinksItem(String key, Link linksItem) {
    if (this.links == null) {
      this.links = new HashMap<>();
    }
    this.links.put(key, linksItem);
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @javax.annotation.Nullable

  public Map<String, Link> getLinks() {
    return links;
  }


  public void setLinks(Map<String, Link> links) {
    this.links = links;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EntityModelDegreetype entityModelDegreetype = (EntityModelDegreetype) o;
    return Objects.equals(this.typename, entityModelDegreetype.typename) &&
        Objects.equals(this.shortcode, entityModelDegreetype.shortcode) &&
        Objects.equals(this.links, entityModelDegreetype.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(typename, shortcode, links);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EntityModelDegreetype {\n");
    sb.append("    typename: ").append(toIndentedString(typename)).append("\n");
    sb.append("    shortcode: ").append(toIndentedString(shortcode)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("typename");
    openapiFields.add("shortcode");
    openapiFields.add("_links");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to EntityModelDegreetype
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!EntityModelDegreetype.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in EntityModelDegreetype is not found in the empty JSON string", EntityModelDegreetype.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!EntityModelDegreetype.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `EntityModelDegreetype` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if ((jsonObj.get("typename") != null && !jsonObj.get("typename").isJsonNull()) && !jsonObj.get("typename").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `typename` to be a primitive type in the JSON string but got `%s`", jsonObj.get("typename").toString()));
      }
      if ((jsonObj.get("shortcode") != null && !jsonObj.get("shortcode").isJsonNull()) && !jsonObj.get("shortcode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `shortcode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("shortcode").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EntityModelDegreetype.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EntityModelDegreetype' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EntityModelDegreetype> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EntityModelDegreetype.class));

       return (TypeAdapter<T>) new TypeAdapter<EntityModelDegreetype>() {
           @Override
           public void write(JsonWriter out, EntityModelDegreetype value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public EntityModelDegreetype read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of EntityModelDegreetype given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of EntityModelDegreetype
  * @throws IOException if the JSON string is invalid with respect to EntityModelDegreetype
  */
  public static EntityModelDegreetype fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EntityModelDegreetype.class);
  }

 /**
  * Convert an instance of EntityModelDegreetype to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

